const SET_LOADING = 'SET_LOADING';
const SET_144_LIST = 'SET_144_LIST';
const SET_CURRENT_GAME_TYPE = 'SET_CURRENT_GAME_TYPE';
const CHECKIN_SELECTED_FIGURE = 'CHECKIN_SELECTED_FIGURE';
const SET_FIGURES_INACTIVE = 'SET_FIGURES_INACTIVE';
// export const DB_FETCH = 'DB_FETCH';
// export const DB_FETCH_SUCCESS = 'DB_FETCH_SUCCESS';
// export const DB_FETCH_FAILED = 'DB_FETCH_FAILED';
// export const SET_NAME_REGISTER = 'SET_NAME_REGISTER';
// export const SET_NAME_LOGIN = 'SET_NAME_LOGIN';
export default {
  SET_LOADING,
  SET_144_LIST,
  SET_CURRENT_GAME_TYPE,
  CHECKIN_SELECTED_FIGURE,
  SET_FIGURES_INACTIVE
};
