const SET_LOADING = 'SET_LOADING';
const SET_144_LIST = 'SET_144_LIST';
const SET_CURRENT_GAME_TYPE = 'SET_CURRENT_GAME_TYPE';

export default {
  SET_LOADING,
  SET_144_LIST,
  SET_CURRENT_GAME_TYPE,
};
