const SET_LOADING = 'SET_LOADING';
const SET_144_LIST = 'SET_144_LIST';
const SET_CURRENT_GAME_TYPE = 'SET_CURRENT_GAME_TYPE';
const CHECKIN_SELECTED_FIGURE = 'CHECKIN_SELECTED_FIGURE';

export default {
  SET_LOADING,
  SET_144_LIST,
  SET_CURRENT_GAME_TYPE,
  CHECKIN_SELECTED_FIGURE,
};
